Repository microsoft/retina, pull requests merged in 2024-10, with the labels that each got.

#799 fix: scope Hubble TLS CronJob's secret access to its namespace
  deploy/hubble/manifests/controller/helm/retina/templates/hubble/tls-cronjob/rolebinding.yaml
Labels: control-plane/hubble

#801 fix(operator): broken CiliumEndpoint garbage collection
  operator/cilium-crds/k8s/fakeresource.go
  operator/cilium-crds/k8s/resources.go
Labels: area/operator, control-plane/hubble

#800 fix: scope operator's CRD permissions to cilium endpoints/identities
  deploy/hubble/manifests/controller/helm/retina/templates/operator/clusterrole.yaml
Labels: control-plane/hubble

#768 chore: add prefix retina_ to eBPF maps so that they are easier to identify
  docs/03-Metrics/plugins/Linux/dropreason.md
  pkg/plugin/common/constants.go
  pkg/plugin/conntrack/_cprog/conntrack.c
  pkg/plugin/conntrack/conntrack_bpfel_arm64.go
  pkg/plugin/conntrack/conntrack_bpfel_x86.go
  pkg/plugin/conntrack/conntrack_linux.go
  pkg/plugin/dropreason/_cprog/drop_reason.c
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/dropreason/kprobe_bpfel_arm64.go
  pkg/plugin/dropreason/kprobe_bpfel_x86.go
  pkg/plugin/filter/_cprog/retina_filter.c
  pkg/plugin/filter/filter_bpfel_arm64.go
  pkg/plugin/filter/filter_bpfel_x86.go
  pkg/plugin/filter/filter_map_linux.go
  pkg/plugin/packetforward/_cprog/packetforward.c
  pkg/plugin/packetforward/packetforward_bpfel_arm64.go
  pkg/plugin/packetforward/packetforward_bpfel_x86.go
  pkg/plugin/packetforward/packetforward_linux.go
  pkg/plugin/packetparser/_cprog/packetparser.c
  pkg/plugin/packetparser/packetparser_bpfel_arm64.go
  pkg/plugin/packetparser/packetparser_bpfel_x86.go
  pkg/plugin/packetparser/packetparser_linux.go
Labels: area/ebpf

#797 fix(grafana/PR#158): fix node selection, metrics name dns, pod-level dash
  deploy/legacy/grafana/dashboards/clusters.json
  deploy/legacy/grafana/dashboards/dns.json
  deploy/legacy/grafana/dashboards/pod-level.json
Labels: type/enhancement, type/fix

#767 feat: make commands to test plugins locally
  test/plugin/Makefile
  test/plugin/packetparser/deployment.yaml
  test/plugin/packetparser/main_linux.go
Labels: type/enhancement, area/infra

#653 fix(capture): remove only managed secret
  docs/04-Captures/managed-storage-account.md
  pkg/controllers/operator/capture/controller.go
Labels: type/fix, area/captures, meta/waiting-for-author

#831 fix(conntrack): delete keys in eBPF instead of user space
  pkg/plugin/conntrack/_cprog/conntrack.c
  pkg/plugin/conntrack/conntrack_bpfel_x86.go
  pkg/plugin/conntrack/conntrack_linux.go
  pkg/plugin/packetparser/packetparser_bpfel_x86.go
Labels: type/enhancement, area/ebpf, lang/c, scope/S

#870 fix: e2e missing dependency - external ServiceMonitor CRD's for retina-operator
  deploy/legacy/manifests/controller/helm/retina/templates/operator.yaml
  test/e2e/framework/kubernetes/get-external-crd.go
  test/e2e/framework/kubernetes/install-retina-helm.go
Labels: area/metrics, area/operator

#892 fix(ct): correctly pass reverse key for deletion from conntrack map
  pkg/plugin/conntrack/_cprog/conntrack.c
Labels: type/fix, area/ebpf

#909 fix: report TCP packets that carried important flags regardless of the report interval
  pkg/plugin/conntrack/_cprog/conntrack.c
Labels: type/fix

#756 chore: refactor packetparser userspace code
  go.mod
  pkg/plugin/packetparser/mocks/mock_types.go
  pkg/plugin/packetparser/packetparser_linux.go
  pkg/plugin/packetparser/packetparser_linux_test.go
  pkg/plugin/packetparser/types_linux.go
Labels: type/enhancement, area/plugins

#916 fix(log): change log level from error to debug when we failed to delete a key in conntrack
  pkg/plugin/conntrack/conntrack_linux.go
Labels: type/fix
