Repository microsoft/retina, pull requests merged in 2024-09, with the labels that each got.

#644 fix: remove namespace from Module.includedNamespaces
  pkg/module/metrics/metrics_module.go
  pkg/module/metrics/metrics_module_test.go
Labels: type/fix

#654 fix: annotation tag in documentation
  docs/02-Installation/03-Config.md
Labels: area/documentation, type/fix

#687 fix: inconsistent label cardinality error in latency metric
  pkg/module/metrics/latency.go
Labels: type/fix

#693 chore: rename prometheus metrics that are supposed to be gauge
  pkg/metrics/interfaces.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/mock_types.go
  pkg/metrics/types.go
  pkg/module/metrics/dns.go
  pkg/module/metrics/dns_test.go
  pkg/module/metrics/drops.go
  pkg/module/metrics/drops_test.go
  pkg/module/metrics/forward.go
  pkg/module/metrics/forward_test.go
  pkg/module/metrics/latency.go
  pkg/module/metrics/latency_test.go
  pkg/module/metrics/tcpflags.go
  pkg/module/metrics/tcpflags_test.go
  pkg/module/metrics/tcpretrans.go
  pkg/module/metrics/types.go
  pkg/plugin/dns/dns_linux_test.go
  pkg/plugin/dns/types_linux.go
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/dropreason/dropreason_linux_test.go
  pkg/plugin/infiniband/infiniband_stats_linux.go
  pkg/plugin/infiniband/infiniband_stats_linux_test.go
  pkg/plugin/linuxutil/ethtool_stats_linux.go
  pkg/plugin/linuxutil/ethtool_stats_linux_test.go
  pkg/plugin/linuxutil/netstat_stats_linux.go
  pkg/plugin/packetforward/packetforward_linux.go
  pkg/plugin/packetparser/packetparser_linux_test.go
  pkg/plugin/windows/hnsstats/hnsstats_windows.go
  pkg/utils/metric_names.go
Labels: type/enhancement, area/metrics

#624 feat(conntrack): conntrack integration with packetparser
  pkg/bpf/setup_linux.go
  pkg/hubble/parser/layer34/parser_linux.go
  pkg/managers/pluginmanager/pluginmanager.go
  pkg/managers/pluginmanager/pluginmanager_test.go
  pkg/module/metrics/latency_test.go
  pkg/plugin/common/constants.go
  pkg/plugin/conntrack/_cprog/conntrack.c
  pkg/plugin/conntrack/_cprog/conntrack.h
  pkg/plugin/conntrack/conntrack_linux.go
  pkg/plugin/conntrack/conntrack_windows.go
  pkg/plugin/conntrack/types_linux.go
  pkg/plugin/dns/dns_linux.go
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/dropreason/kprobe_bpfel_arm64.go
  pkg/plugin/dropreason/kprobe_bpfel_x86.go
  pkg/plugin/packetparser/_cprog/dynamic.h
  pkg/plugin/packetparser/_cprog/packetparser.c
  pkg/plugin/packetparser/_cprog/packetparser.h
  pkg/plugin/packetparser/packetparser_bpfel_arm64.go
  pkg/plugin/packetparser/packetparser_bpfel_x86.go
  pkg/plugin/packetparser/packetparser_linux.go
  pkg/plugin/packetparser/packetparser_linux_test.go
  pkg/plugin/packetparser/types_linux.go
  pkg/plugin/tcpretrans/tcpretrans_linux.go
  pkg/utils/flow_utils.go
  pkg/utils/metadata_linux.pb.go
  pkg/utils/metadata_windows.pb.go
  pkg/utils/utils_linux_test.go
Labels: type/enhancement, lang/go, area/plugins, area/ebpf, priority/0, lang/c, scope/L, area/flows

#721 fix: correctly determine traffic direction in conntrack
  pkg/plugin/conntrack/_cprog/conntrack.c
Labels: type/fix

#722 chore: update Go build image to 1.23.1
  controller/Dockerfile
  controller/Dockerfile.gogen
  controller/Dockerfile.proto
  controller/Dockerfile.windows-2019
  controller/Dockerfile.windows-2022
  controller/Dockerfile.windows-cgo
  controller/Dockerfile.windows-native
  go.mod
  operator/Dockerfile
  operator/Dockerfile.windows-2019
  operator/Dockerfile.windows-2022
  test/image/Dockerfile
Labels: area/dependencies

#745 chore: bump Hubble CLI to v1.16.1
  Makefile
  controller/Dockerfile
Labels: dependencies

#762 feat: revamp site + update docs
  .github/.markdownlint.json
  README.md
  docs/02-Installation/03-Config.md
  docs/03-Metrics/modes/basic.md
  docs/03-Metrics/plugins/Linux/ciliumeventobserver.md
  docs/03-Metrics/plugins/Linux/dns.md
  docs/03-Metrics/plugins/Linux/dropreason.md
  docs/03-Metrics/plugins/Linux/infiniband.md
  docs/03-Metrics/plugins/Linux/linuxutil.md
  docs/03-Metrics/plugins/Linux/packetforward.md
  docs/03-Metrics/plugins/Linux/packetparser.md
  docs/03-Metrics/plugins/Linux/tcpretrans.md
  docs/03-Metrics/plugins/Windows/hnsstats.md
  docs/03-Metrics/plugins/packetforward.md
  docs/03-Metrics/plugins/packetparser.md
  docs/03-Metrics/plugins/readme.md
  docs/03-Metrics/plugins/tcpretrans.md
  site/.gitignore
  site/docusaurus.config.js
  site/docusaurus.config.ts
  site/package-lock.json
  site/package.json
  site/sidebars.js
  site/sidebars.ts
  site/site/package-lock.json
  site/src/components/Features.module.css
  site/src/components/Features.tsx
  site/src/components/LandingPage.module.css
  site/src/components/LandingPage.tsx
  site/src/components/cni.svg
  site/src/components/eBPF.svg
  site/src/components/hex.svg
  site/src/components/hubble-light.svg
  site/src/components/kubernetes.svg
  site/src/components/prometheus.svg
  site/src/components/square1.svg
  site/src/components/square2.svg
  site/src/components/wireshark.svg
  site/src/css/custom.css
  site/src/pages/index.js
  site/src/pages/index.tsx
  site/src/pages/markdown-page.md
  site/src/prismColorTheme.ts
  site/start-dev.sh
  site/static/.nojekyll
  site/static/img/android-chrome-192x192.png
  site/static/img/android-chrome-512x512.png
  site/static/img/apple-touch-icon.png
  site/static/img/favicon-16x16.png
  site/static/img/favicon-32x32.png
  site/static/img/favicon.ico
  site/static/img/favicon.svg
  site/static/img/retina-features.png
  site/static/img/retina-logo-dark.svg
  site/static/img/retina-logo.png
  site/static/img/retina-logo.svg
  site/static/img/retina-social-card.png
  site/static/img/site.webmanifest
  site/tsconfig.json
Labels: area/documentation, type/enhancement
