Repository microsoft/retina, pull requests merged in 2024-06, with the labels that each got.

#430 fix: updated llvm version in docs to 16
  docs/contributing/developing.md
Labels: area/documentation, type/fix, scope/S

#388 fix: remove inactive connections' IP addresses from tcp_connection_remote metric
  pkg/plugin/linuxutil/linuxutil_linux.go
  pkg/plugin/linuxutil/netstat_stats_linux.go
  pkg/plugin/linuxutil/netstat_stats_linux_test.go
  pkg/plugin/linuxutil/types_linux.go
Labels: type/fix, area/metrics, area/plugins, priority/0, scope/S

#304 feat: infiniband plugin
  docs/metrics/plugins/infiniband.md
  pkg/metrics/metrics.go
  pkg/metrics/types.go
  pkg/plugin/infiniband/Makefile
  pkg/plugin/infiniband/embedded_filesystem.go
  pkg/plugin/infiniband/infiniband_linux.go
  pkg/plugin/infiniband/infiniband_linux_test.go
  pkg/plugin/infiniband/infiniband_mock_generated.go
  pkg/plugin/infiniband/infiniband_stats_linux.go
  pkg/plugin/infiniband/infiniband_stats_linux_test.go
  pkg/plugin/infiniband/types_linux.go
  pkg/plugin/linuxutil/linuxutil_mock_generated.go
  pkg/plugin/registry/registry_linux.go
  pkg/utils/attr_utils.go
  pkg/utils/metric_names.go
  site/sidebars.js
  test/plugin/infiniband/main_linux.go
Labels: type/enhancement, area/plugins, priority/0

#438 fix(e2e): add an extra nslookup when testing for advanced DNS metrics
  test/e2e/scenarios/dns/scenarios.go
Labels: type/fix, area/infra, scope/S

#442 feat: migrate azure/login gha to oidc
  .github/workflows/e2e.yaml
  .github/workflows/images.yaml
Labels: type/enhancement, area/infra, priority/0, scope/S

#250 test(ci): add azp image builds
  .github/workflows/images.yaml
  .pipelines/cg-pipeline.yaml
  Makefile
  controller/Dockerfile.windows-2019
  controller/Dockerfile.windows-2022
  controller/Dockerfile.windows-cgo
  controller/Dockerfile.windows-native
  controller/Dockerfile.windows-native.dockerignore
  deploy/manifests/controller/helm/retina/templates/daemonset.yaml
  windows/docker/DockerBuild.ps1
  windows/docker/DockerBuildModule.psm1
  windows/docker/notes.md
Labels: type/enhancement, area/infra, priority/1, scope/M

#443 fix(#139): do not check for host endianness in IP conversion
  pkg/utils/utils_linux.go
Labels: type/fix, area/plugins, scope/S

#456 fix: invoke SetLogger for controller-runtime manager
  controller/main.go
Labels: type/fix, area/controllers, priority/0, scope/S

#467 fix: make command for windows builds not working correctly
  .github/workflows/images.yaml
Labels: type/fix, area/infra

#457 refactor: removed usages of unsafe package in plugins
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/dropreason/dropreason_linux_test.go
  pkg/plugin/packetparser/packetparser_linux.go
Labels: type/fix, area/plugins, priority/1, scope/S

#509 chore: update krew release bot condition
  .github/workflows/goreleaser.yaml
Labels: type/fix
