Repository microsoft/retina, pull requests merged in 2024-11, with the labels that each got.

#894 feat: Print capture output name when running retina capture create
  pkg/capture/capture_manager.go
  pkg/capture/capture_manager_test.go
  pkg/capture/constants/job_env.go
  pkg/capture/crd_to_job.go
  pkg/capture/crd_to_job_test.go
  pkg/capture/file/capture_filename.go
  pkg/capture/file/timestamp.go
  pkg/capture/provider/interface.go
  pkg/capture/provider/mock_network_capture.go
  pkg/capture/provider/network_capture_common.go
  pkg/capture/provider/network_capture_test.go
  pkg/capture/provider/network_capture_unix.go
  pkg/capture/provider/network_capture_win.go
Labels: type/enhancement, area/captures

#990 chore(deps): bump docusaurus to 3.6.1 in /site
  site/package-lock.json
  site/package.json
Labels: dependencies

#996 fix: add retract directive for v0.10.0
  go.mod
Labels: type/fix

#998 chore: bump agent's hubble to v1.16.3
  Makefile
  controller/Dockerfile
  deploy/hubble/manifests/controller/helm/retina/templates/operator/deployment.yaml
Labels: area/controllers, control-plane/hubble

#997 fix(ethtool): ignore lxc and azv interfaces
  pkg/plugin/linuxutil/ethtool_stats_linux.go
Labels: type/enhancement, area/controllers

#1003 fix(ethtool): enable filtering out non-err/drop stats
  pkg/plugin/linuxutil/linuxutil_linux.go
Labels: type/fix, area/controllers

#891 fix(CLI): add tool name to Retina CLI help message
  cli/cmd/root.go
Labels: area/documentation, type/fix, area/captures, scope/S

#1012 fix: add kubectl-retina manifest
  .github/workflows/images.yaml
  .pipelines/cg-pipeline.yaml
Labels: type/enhancement

#1018 fix: add retraction for v0.10.0 via v0.10.1 in go mod
  go.mod
Labels: type/fix

#1035 chore: revert: use mariner core base image for kubectl-retina
  cli/Dockerfile
Labels: type/fix

#1008 feat(helm): add support for priorityClassName
  deploy/hubble/manifests/controller/helm/retina/templates/agent/daemonset.yaml
  deploy/hubble/manifests/controller/helm/retina/templates/operator/deployment.yaml
  deploy/hubble/manifests/controller/helm/retina/values.yaml
  deploy/legacy/manifests/controller/helm/retina/templates/daemonset.yaml
  deploy/legacy/manifests/controller/helm/retina/templates/operator.yaml
  deploy/legacy/manifests/controller/helm/retina/values.yaml
Labels: type/enhancement, scope/S

#568 fix: capture commands should respect --namespace
  cli/cmd/capture/capture.go
  cli/cmd/capture/create.go
  cli/cmd/capture/delete.go
  cli/cmd/capture/download.go
  cli/cmd/capture/list.go
Labels: lang/go, type/fix, area/captures, scope/S
