Repository microsoft/retina, pull requests merged in 2024-03, with the labels that each got.

#38 feat: publish to ghcr
  .github/workflows/images.yaml
  Makefile
Labels: enhancement

#39 chore: plugins godocs + refactor/cleanup
  pkg/bpf/setup.go
  pkg/managers/controllermanager/controllermanager_test.go
  pkg/managers/pluginmanager/pluginmanager_test.go
  pkg/plugin/api/mock/mock_plugin.go
  pkg/plugin/api/types.go
  pkg/plugin/common/common_linux.go
  pkg/plugin/common/constants.go
  pkg/plugin/dns/dns_linux.go
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/dropreason/kprobe_bpf.o
  pkg/plugin/dropreason/kprobe_bpfel_arm64.go
  pkg/plugin/dropreason/kprobe_bpfel_arm64.o
  pkg/plugin/dropreason/kprobe_bpfel_x86.go
  pkg/plugin/dropreason/kprobe_bpfel_x86.o
  pkg/plugin/dropreason/types_linux.go
  pkg/plugin/filter/filter_bpfel_arm64.o
  pkg/plugin/filter/filter_bpfel_x86.o
  pkg/plugin/filter/filter_map_linux.go
  pkg/plugin/linuxutil/linuxutil.go
  pkg/plugin/linuxutil/linuxutil_mock_generated.go
  pkg/plugin/packetforward/packetforward_bpf.o
  pkg/plugin/packetforward/packetforward_bpfel_arm64.o
  pkg/plugin/packetforward/packetforward_bpfel_x86.o
  pkg/plugin/packetforward/packetforward_linux.go
  pkg/plugin/packetparser/packetparser_bpf.o
  pkg/plugin/packetparser/packetparser_bpfel_arm64.go
  pkg/plugin/packetparser/packetparser_bpfel_arm64.o
  pkg/plugin/packetparser/packetparser_bpfel_x86.go
  pkg/plugin/packetparser/packetparser_bpfel_x86.o
  pkg/plugin/packetparser/packetparser_linux.go
  pkg/plugin/registry/registry_linux.go
  pkg/plugin/tcpretrans/tcpretrans_linux.go
  pkg/plugin/windows/hnsstats/hnsstats_windows.go
Labels: documentation

#41 fix: windows linter issue
  .github/workflows/test.yaml
  controller/Dockerfile.controller
  init/retina/main_linux.go
  pkg/bpf/setup_linux.go
  pkg/plugin/dns/dns_linux_test.go
  pkg/plugin/dns/types_linux.go
  pkg/plugin/dropreason/dropreason_linux_test.go
  pkg/plugin/filter/filter_map_linux_test.go
  pkg/plugin/linuxutil/ethtool_stats_linux.go
  pkg/plugin/linuxutil/ethtool_stats_linux_test.go
  pkg/plugin/linuxutil/linuxutil_linux.go
  pkg/plugin/linuxutil/linuxutil_linux_test.go
  pkg/plugin/linuxutil/netstat_stats_linux.go
  pkg/plugin/linuxutil/netstat_stats_linux_test.go
  pkg/plugin/linuxutil/types_linux.go
  pkg/plugin/packetparser/packetparser_linux_test.go
  pkg/plugin/tcpretrans/types_linux.go
  pkg/telemetry/heartbeat_windows_test.go
  pkg/watchers/endpoint/endpoint_linux_test.go
  test/plugin/dns/main_linux.go
  test/plugin/dropreason/main_linux.go
  test/plugin/linuxutil/main_linux.go
  test/plugin/packetforward/main_linux.go
  test/plugin/packetparser/main_linux.go
Labels: fix

#43 fix: increase CodeQL timeout
  .github/workflows/codeql.yaml
Labels: fix

#44 docs: update README with report cards + fix misc issues
  README.md
  pkg/capture/crd_to_job.go
  pkg/capture/provider/network_capture_win.go
  pkg/controllers/cache/cache_test.go
  pkg/controllers/daemon/namespace/namespace_controller_test.go
  pkg/deprecated/cache/cache_test.go
  pkg/enricher/enricher.go
  pkg/enricher/enricher_test.go
  pkg/managers/filtermanager/manager_test.go
  pkg/managers/filtermanager/types.go
  pkg/managers/pluginmanager/pluginmanager.go
  pkg/managers/pluginmanager/pluginmanager_test.go
  pkg/managers/watchermanager/watchermanager_test.go
  pkg/metrics/types.go
  pkg/module/metrics/dns.go
  pkg/module/metrics/dns_test.go
  pkg/module/metrics/drops.go
  pkg/module/metrics/drops_test.go
  pkg/module/metrics/forward.go
  pkg/module/metrics/forward_test.go
  pkg/module/metrics/latency_test.go
  pkg/module/metrics/metrics_module.go
  pkg/module/metrics/metrics_module_test.go
  pkg/module/metrics/tcpflags.go
  pkg/module/metrics/tcpflags_test.go
  pkg/module/metrics/tcpretrans.go
  pkg/module/metrics/types.go
  pkg/plugin/dns/dns_linux_test.go
  pkg/plugin/dns/types_linux.go
  pkg/plugin/dropreason/dropreason_linux_test.go
  pkg/plugin/filter/filter_map_linux_test.go
  pkg/plugin/linuxutil/ethtool_stats_linux_test.go
  pkg/plugin/linuxutil/netstat_stats_linux.go
  pkg/plugin/linuxutil/netstat_stats_linux_test.go
  pkg/plugin/linuxutil/types_linux.go
  pkg/plugin/mockplugin/mockplugin.go
  pkg/plugin/packetforward/packetforward_linux.go
  pkg/plugin/packetforward/packetforward_linux_test.go
  pkg/plugin/packetparser/_cprog/dynamic.h
  pkg/plugin/packetparser/packetparser_linux_test.go
  pkg/plugin/packetparser/types_linux.go
  pkg/plugin/tcpretrans/types_linux.go
  pkg/pubsub/pubsub.go
  pkg/server/server.go
  pkg/telemetry/telemetry_test.go
  pkg/utils/utils_linux_test.go
  pkg/watchers/apiserver/apiserver_test.go
  test/enricher/main.go
  test/integration/plugins/dns/dns_suite_test.go
  test/integration/plugins/dropreason/dropreason_suite_test.go
  test/integration/plugins/forward/forward_suite_test.go
Labels: documentation, fix

#45 feat: replace ACR and MCR with GHCR
  controller/Dockerfile.controller
  deploy/manifests/controller/helm/retina/values.yaml
  docs/captures/cli.md
  docs/troubleshooting/capture.md
  hack/tools/kapinger/manifests/deploy.yaml
  pkg/capture/constants/job_specification.go
  pkg/capture/crd_to_job_test.go
  pkg/capture/utils/capture_image_test.go
  scripts/windows.ps1
  test/goldpinger/daemonset.yaml
  test/goldpinger/deployment.yaml
  test/integration/capture/capture_suite_test.go
  test/scale/example-deployment.yaml
  test/trafficgen/kapinger.yaml
  windows/manifests/windows.yaml
Labels: enhancement

#73 fix: remove dupe section from README
  README.md
Labels: documentation, fix

#69 chore: add clarity to telemetry enablement
  captureworkload/main.go
  controller/main.go
  deploy/manifests/controller/helm/retina/values.yaml
  docs/troubleshooting/basic-metrics.md
  init/retina/main_linux.go
  operator/main.go
  pkg/capture/capture_manager.go
  pkg/managers/controllermanager/controllermanager.go
  pkg/telemetry/telemetry.go
Labels: enhancement

#77 feat: add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#84 fix: remove push images
  .github/workflows/images.yaml
  Makefile
Labels: fix, area/infra

#112 feat: adds goreleaser
  .github/workflows/golangci-lint.yaml
  .github/workflows/goreleaser.yaml
  .github/workflows/images.yaml
  .github/workflows/release-images.yaml
  .gitignore
  .goreleaser.yaml
  Makefile
  cli/Dockerfile.kubectl-retina
  hack/tools/tools.go
  pkg/capture/provider/network_capture_unix.go
  pkg/capture/provider/network_capture_win.go
  pkg/telemetry/heartbeat_unix.go
  pkg/telemetry/heartbeat_unix_test.go
Labels: enhancement, area/infra

#120 fix: drop dependency on remove kubectl-retina job
  .github/workflows/release-images.yaml
Labels: fix, area/infra

#121 feat: add PR template and CONTRIBUTING
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
  CONTRIBUTING.md
Labels: documentation, area/infra

#126 chore: package kubectl retina as tar.gz (zip for windows) via goreleaser
  .goreleaser.yaml
Labels: fix

#127 feat: publish charts as OCI artifacts to GHCR
  .github/workflows/release-charts.yaml
  deploy/manifests/controller/helm/retina/Chart.yaml
  deploy/manifests/controller/helm/retina/values.yaml
Labels: enhancement, area/infra

#136 fix: move PR template to default location
  .github/pull_request.md
Labels: documentation

#144 chore: update GHA workflows
  .github/dependabot.yaml
  .github/workflows/stale.yaml
Labels: type/fix, area/infra

#143 docs: update instructions for building kubectl-retina
  .github/workflows/integration.yaml
  .gitignore
  Makefile
  README.md
  docs/installation/cli.md
  hack/tools/go.mod
  hack/tools/go.sum
Labels: area/documentation

#157 fix(helm): remove duplicate nodeSelector
  deploy/manifests/controller/helm/retina/templates/daemonset.yaml
Labels: type/enhancement, area/infra

#156 feat(helm): customize nodeselector and tolerations
  deploy/manifests/controller/helm/retina/templates/daemonset.yaml
  deploy/manifests/controller/helm/retina/values.yaml
Labels: type/enhancement, area/infra

#159 feat: cache Go's build artifacts in dockerfiles
  controller/Dockerfile.controller
  controller/Dockerfile.windows-2019
  controller/Dockerfile.windows-2022
  operator/Dockerfile
  operator/Dockerfile.windows-2019
  operator/Dockerfile.windows-2022
Labels: type/enhancement, area/infra

#142 docs: update instructions for helm install to use GHCR
  .github/pull_request_template.md
  .github/workflows/release-charts.yaml
  Makefile
  README.md
  deploy/manifests/controller/helm/retina/values.yaml
  docs/contributing/readme.md
  docs/installation/setup.md
Labels: area/documentation

#154 feat(helm): add podmonitor
  deploy/manifests/controller/helm/retina/templates/daemonset.yaml
  deploy/manifests/controller/helm/retina/templates/podmonitor.yaml
  deploy/manifests/controller/helm/retina/values.yaml
Labels: type/enhancement, area/infra, priority/1

#109 feat: run e2e in azure cluster.
  .github/workflows/integration.yaml
  test/e2e/framework/azure/create-cluster-with-npm.go
  test/e2e/framework/generic/load-tag.go
  test/e2e/framework/kubernetes/install-retina-helm.go
  test/e2e/scenarios/retina/retina_scenarios_test.go
Labels: type/enhancement, area/infra, priority/0

#140 chore: change parse ts func in packetparser
  pkg/plugin/linuxutil/linuxutil_mock_generated.go
  pkg/plugin/packetparser/_cprog/packetparser.c
  pkg/plugin/packetparser/_cprog/packetparser.h
  pkg/plugin/packetparser/packetparser_bpf.o
  pkg/plugin/packetparser/packetparser_bpfel_arm64.o
  pkg/plugin/packetparser/packetparser_bpfel_x86.o
Labels: type/fix, area/ebpf, priority/0

#190 feat: Build and run e2e after PR is added to merge queue.
  .github/workflows/codeql.yaml
  .github/workflows/commit-message.yaml
  .github/workflows/docs.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/images.yaml
  .github/workflows/integration.yaml
  .github/workflows/markdownlint.yaml
  .github/workflows/test.yaml
Labels: area/infra, priority/0

#195 fix: run conditions on step level when using matrix strategy.
  .github/workflows/codeql.yaml
  .github/workflows/golangci-lint.yaml
Labels: area/infra, priority/0

#194 feat: use krew-release-bot to automate releasing new version to krew-index
  .github/workflows/goreleaser.yaml
  .krew.yaml
Labels: type/enhancement, area/infra

#187 fix: spelling in the PR template
  .github/pull_request_template.md
Labels: area/documentation, type/fix, priority/2

#193 docs: add instructions to install the CLI through Krew
  .goreleaser.yaml
  README.md
  docs/installation/cli.md
  docs/installation/setup.md
Labels: area/documentation, type/enhancement, priority/1

#165 fix: failed to initialize filter map
  pkg/plugin/filter/filter_map_linux.go
Labels: type/fix, area/plugins, priority/0
