Repository microsoft/retina, pull requests merged in 2024-12, with the labels that each got.

#1095 fix: name flag dereference
  cli/cmd/capture/capture.go
  cli/cmd_test.go
Labels: type/fix, area/captures

#1098 feat: let plugins self-register
  pkg/managers/controllermanager/controllermanager.go
  pkg/managers/controllermanager/controllermanager_test.go
  pkg/managers/pluginmanager/cells_linux.go
  pkg/managers/pluginmanager/pluginmanager.go
  pkg/managers/pluginmanager/pluginmanager_test.go
  pkg/plugin/ciliumeventobserver/ciliumeventobserver_linux.go
  pkg/plugin/ciliumeventobserver/types_linux.go
  pkg/plugin/dns/dns_linux.go
  pkg/plugin/dns/dns_linux_test.go
  pkg/plugin/dns/types_linux.go
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/dropreason/dropreason_linux_test.go
  pkg/plugin/dropreason/types_linux.go
  pkg/plugin/hnsstats/hnsstats_windows.go
  pkg/plugin/hnsstats/hnsstats_windows_test.go
  pkg/plugin/hnsstats/types_windows.go
  pkg/plugin/hnsstats/vfp_counters_windows.go
  pkg/plugin/include_linux.go
  pkg/plugin/include_windows.go
  pkg/plugin/infiniband/infiniband_linux.go
  pkg/plugin/infiniband/infiniband_linux_test.go
  pkg/plugin/infiniband/types_linux.go
  pkg/plugin/linuxutil/linuxutil_linux.go
  pkg/plugin/linuxutil/linuxutil_linux_test.go
  pkg/plugin/linuxutil/types_linux.go
  pkg/plugin/mock/plugin.go
  pkg/plugin/mockplugin/mockplugin.go
  pkg/plugin/packetforward/packetforward_linux.go
  pkg/plugin/packetforward/packetforward_linux_test.go
  pkg/plugin/packetforward/types_linux.go
  pkg/plugin/packetparser/packetparser_linux.go
  pkg/plugin/packetparser/packetparser_linux_test.go
  pkg/plugin/packetparser/types_linux.go
  pkg/plugin/pktmon/pktmon_windows.go
  pkg/plugin/plugin.go
  pkg/plugin/registry/registry.go
  pkg/plugin/registry/registry_linux.go
  pkg/plugin/registry/registry_windows.go
  pkg/plugin/tcpretrans/tcpretrans_linux.go
  pkg/plugin/tcpretrans/types_linux.go
Labels: type/enhancement, lang/go, area/plugins, priority/1, scope/M

#1108 fix(goreleaser): update ldflags for building Retina CLI
  .goreleaser.yaml
Labels: type/fix, area/infra

#1100 fix: filtermanager cache and cache test races
  pkg/managers/filtermanager/cache.go
  pkg/managers/filtermanager/cache_test.go
  pkg/managers/filtermanager/manager_linux.go
Labels: type/fix

#1127 chore(go): update go.mod and base images to go 1.23.4
  cli/Dockerfile
  controller/Dockerfile
  controller/Dockerfile.gogen
  controller/Dockerfile.proto
  controller/Dockerfile.windows-2019
  controller/Dockerfile.windows-2022
  controller/Dockerfile.windows-cgo
  controller/Dockerfile.windows-native
  go.mod
  operator/Dockerfile
  operator/Dockerfile.windows-2019
  operator/Dockerfile.windows-2022
  test/image/Dockerfile
Labels: lang/go, type/fix, dependencies

#1102 feat(ct-metrics): BPF implementation
  deploy/hubble/manifests/controller/helm/retina/templates/agent/configmap.yaml
  deploy/legacy/manifests/controller/helm/retina/templates/configmap.yaml
  deploy/legacy/manifests/controller/helm/retina/values.yaml
  pkg/config/config.go
  pkg/plugin/conntrack/_cprog/conntrack.c
  pkg/plugin/conntrack/_cprog/dynamic.h
  pkg/plugin/conntrack/conntrack_bpfel_arm64.go
  pkg/plugin/conntrack/conntrack_bpfel_x86.go
  pkg/plugin/conntrack/conntrack_linux.go
  pkg/plugin/conntrack/conntrack_linux_test.go
  pkg/plugin/conntrack/types_linux.go
  pkg/plugin/packetparser/_cprog/packetparser.c
  pkg/plugin/packetparser/packetparser_bpfel_arm64.go
  pkg/plugin/packetparser/packetparser_bpfel_x86.go
  pkg/plugin/packetparser/packetparser_linux.go
  pkg/plugin/packetparser/packetparser_linux_test.go
Labels: type/enhancement, area/ebpf, lang/c, scope/M

#1160 deps: bump golang.org/x/net from 0.32.0 to 0.33.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/kapinger/go.mod
  hack/tools/kapinger/go.sum
Labels: area/dependencies, lang/go

#1161 feat: automate Hubble version bump
  .github/workflows/update-hubble.yaml
  Makefile
  controller/Dockerfile
Labels: area/infra

#1167 deps: bump Hubble from 1.16.3 to 1.16.5
  Makefile
  controller/Dockerfile
Labels: area/dependencies
