Repository microsoft/retina, pull requests merged in 2024-08, with the labels that each got.

#574 fix: move version and appinsightsID to a centralized location (internal/buildinfo)
  Makefile
  captureworkload/main.go
  cmd/hubble/cells_linux.go
  cmd/hubble/daemon_main_linux.go
  cmd/hubble_linux.go
  cmd/legacy/daemon.go
  controller/Dockerfile
  controller/Dockerfile.windows-2019
  controller/Dockerfile.windows-2022
  controller/Dockerfile.windows-native
  init/retina/main_linux.go
  internal/buildinfo/buildinfo.go
  operator/Dockerfile
  operator/Dockerfile.windows-2019
  operator/Dockerfile.windows-2022
  operator/cmd/cilium-crds/cells_linux.go
  operator/cmd/cilium-crds/root_linux.go
  operator/cmd/cilium-crds/zap_linux.go
  operator/cmd/legacy/deployment.go
Labels: type/fix

#556 feat: add data aggregation level
  cmd/hubble/daemon_main_linux.go
  cmd/legacy/daemon.go
  controller/Dockerfile
  controller/Dockerfile.windows-2019
  controller/Dockerfile.windows-2022
  controller/Dockerfile.windows-cgo
  controller/Dockerfile.windows-native
  deploy/hubble/manifests/controller/helm/retina/templates/agent/configmap.yaml
  deploy/hubble/manifests/controller/helm/retina/values.yaml
  deploy/legacy/manifests/controller/helm/retina/templates/configmap.yaml
  deploy/legacy/manifests/controller/helm/retina/values.yaml
  docs/concepts/dataAggregation.md
  docs/installation/config.md
  operator/Dockerfile
  operator/Dockerfile.windows-2019
  operator/Dockerfile.windows-2022
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/hubble_config_linux.go
  pkg/config/testwith/config.yaml
  pkg/managers/controllermanager/controllermanager.go
  pkg/plugin/dropreason/dropreason_linux_test.go
  pkg/plugin/packetparser/packetparser_linux.go
  pkg/plugin/packetparser/packetparser_linux_test.go
  pkg/servermanager/cell_linux.go
Labels: area/plugins

#586 fix: update readdirs in infiniband plugin
  pkg/plugin/infiniband/filesystem_test.go
  pkg/plugin/infiniband/infiniband_linux.go
  pkg/plugin/infiniband/infiniband_stats_linux.go
  pkg/plugin/infiniband/infiniband_stats_linux_test.go
  pkg/plugin/infiniband/types_linux.go
Labels: lang/go, type/fix, area/plugins, priority/1, scope/S

#604 docs(development): caveat about checking llvm installation
  docs/contributing/developing.md
Labels: area/documentation

#611 chore: bump actions/checkout from v3 to v4 in test and trivy
  .github/workflows/test.yaml
  .github/workflows/trivy.yaml
Labels: area/dependencies

#623 fix: add node OS upgrade channel for e2e cluster creation
  test/e2e/framework/azure/create-cluster-with-npm.go
Labels: type/fix, area/infra

#626 chore: update Go image used in Dockerfiles to 1.22.4
  controller/Dockerfile
  controller/Dockerfile.gogen
  controller/Dockerfile.proto
  controller/Dockerfile.windows-2019
  controller/Dockerfile.windows-2022
  controller/Dockerfile.windows-cgo
  controller/Dockerfile.windows-native
  go.mod
  operator/Dockerfile
  operator/Dockerfile.windows-2019
  operator/Dockerfile.windows-2022
  test/image/Dockerfile
Labels: dependencies

#629 chore: bump hubble version + use mariner distroless image for operator
  controller/Dockerfile
  operator/Dockerfile
Labels: dependencies

#630 chore: bump hubble version in Makefile
  Makefile
Labels: dependencies

#575 feat(capture): add managed storage account support
  deploy/legacy/manifests/controller/helm/retina/templates/operator.yaml
  deploy/legacy/manifests/controller/helm/retina/values.yaml
  docs/captures/img/capture-managed-storage-account.png
  docs/captures/managed-storage-account.md
  docs/captures/readme.md
  go.mod
  go.sum
  operator/Dockerfile
  operator/cmd/legacy/deployment.go
  pkg/capture/outputlocation/managed/doc.go
  pkg/capture/outputlocation/managed/storageaccount.go
  pkg/config/capture.go
  pkg/controllers/operator/capture/controller.go
  pkg/controllers/operator/capture/doc.go
  pkg/provider/azure/clients/azclients.go
  pkg/provider/azure/clients/doc.go
  pkg/provider/azure/clients/types.go
Labels: type/enhancement, area/captures, priority/1, scope/M

#613 chore(docs): add link to data aggregation page in sidebar
  docs/concepts/dataAggregation.md
  docs/installation/img/prom-targets.png
  docs/metrics/plugins/readme.md
  docs/troubleshooting/basic-metrics.md
  docs/troubleshooting/imgs/prom-retina-config.png
  docs/troubleshooting/imgs/prom-retina-service-discovery1.png
  docs/troubleshooting/imgs/prom-retina-service-discovery2.png
  docs/troubleshooting/imgs/prometheus-retina-targets.png
  docs/troubleshooting/imgs/prometheus-retina-targets1.png
  docs/troubleshooting/imgs/prometheus-retina-targets2.png
  site/package-lock.json
  site/package.json
  site/sidebars.js
Labels: area/documentation

#647 fix(docs): update broken link
  docs/metrics/plugins/ciliumeventobserver.md
Labels: area/documentation, type/fix

#612 fix: init container should read config for enabling telemetry
  deploy/hubble/manifests/controller/helm/retina/templates/agent/daemonset.yaml
  deploy/legacy/manifests/controller/helm/retina/templates/daemonset.yaml
  init/retina/main_linux.go
Labels: type/fix, scope/S

#625 chore: add CPU profile to telemetry heartbeat
  captureworkload/main.go
  cmd/legacy/daemon.go
  operator/cmd/legacy/deployment.go
  pkg/shared/telemetry/cell_linux.go
  pkg/telemetry/noop_perf.go
  pkg/telemetry/perf.go
  pkg/telemetry/perf_unix.go
  pkg/telemetry/perf_windows.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
Labels: type/enhancement, area/metrics

#666 fix: remove fatals and panics + fix loggings in init container
  init/retina/main_linux.go
  pkg/bpf/setup_linux.go
  pkg/ciliumfs/setup_linux.go
Labels: type/enhancement, type/fix

#684 fix: ib chart mounts and update docs
  README.md
  deploy/legacy/manifests/controller/helm/retina/templates/daemonset.yaml
Labels: area/documentation, type/fix, area/plugins

#620 fix: Implement a dynamic temporary cache that tracks network interfaces that do not support the ethtool operation.
  pkg/plugin/linuxutil/ethtool_handle_linux.go
  pkg/plugin/linuxutil/ethtool_stats_linux.go
  pkg/plugin/linuxutil/ethtool_stats_linux_test.go
  pkg/plugin/linuxutil/linuxutil_linux.go
  pkg/plugin/linuxutil/types_linux.go
  pkg/plugin/packetparser/packetparser_linux.go
Labels: type/fix, area/plugins

#610 feat(conntrack): bpf code for conntrack + conntrack GC
  pkg/bpf/setup_linux.go
  pkg/plugin/common/constants.go
  pkg/plugin/conntrack/_cprog/conntrack.c
  pkg/plugin/conntrack/_cprog/conntrack.h
  pkg/plugin/conntrack/_cprog/placeholder.go
  pkg/plugin/conntrack/conntrack_bpfel_arm64.go
  pkg/plugin/conntrack/conntrack_bpfel_arm64.o
  pkg/plugin/conntrack/conntrack_bpfel_x86.go
  pkg/plugin/conntrack/conntrack_bpfel_x86.o
  pkg/plugin/conntrack/conntrack_linux.go
  pkg/plugin/conntrack/conntrack_windows.go
  pkg/plugin/conntrack/doc.go
  pkg/plugin/conntrack/types_linux.go
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/filter/filter_map_linux.go
  pkg/plugin/packetparser/packetparser_linux.go
Labels: type/enhancement, lang/go, area/ebpf, priority/0, lang/c, scope/M

#686 chore: invoke rlimit.RemoveMemLock only once in main thread
  cmd/hubble/daemon_main_linux.go
  cmd/legacy/daemon.go
  pkg/plugin/conntrack/conntrack_linux.go
  pkg/plugin/dns/dns_linux.go
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/packetforward/packetforward_linux.go
  pkg/plugin/packetparser/packetparser_linux.go
  pkg/plugin/tcpretrans/tcpretrans_linux.go
Labels: type/fix
