Repository microsoft/retina, pull requests merged in 2024-05, with the labels that each got.

#215 feat: select interface based on default route instead of hardcoded eth0 for packetparser plugin
  go.mod
  pkg/plugin/packetparser/packetparser_linux.go
  pkg/plugin/packetparser/types_linux.go
  pkg/utils/utils_linux.go
  pkg/utils/utils_linux_test.go
Labels: type/enhancement, lang/go, area/plugins, priority/1

#332 fix: fail pipeline on failure to build/push image
  Makefile
  controller/Dockerfile
  controller/main.go
Labels: type/fix, area/infra, priority/0, scope/S

#295 feat: Add s3 upload output for capture
  cli/cmd/capture/create.go
  crd/api/v1alpha1/capture_types.go
  crd/api/v1alpha1/zz_generated.deepcopy.go
  deploy/manifests/controller/helm/retina/crds/retina.sh_captures.yaml
  docs/CRDs/Capture.md
  docs/captures/cli.md
  go.mod
  go.sum
  pkg/capture/capture_manager.go
  pkg/capture/constants/job_env.go
  pkg/capture/constants/job_specification.go
  pkg/capture/crd_to_job.go
  pkg/capture/outputlocation/output_test.go
  pkg/capture/outputlocation/s3.go
  samples/capture/node-s3upload-aws.yaml
  samples/capture/node-s3upload-minio.yaml
Labels: type/enhancement, lang/go, area/captures, priority/1, scope/M

#334 fix: add empty .o files for go mod vendor to work
  pkg/plugin/dropreason/kprobe_bpfel_arm64.o
  pkg/plugin/dropreason/kprobe_bpfel_x86.o
  pkg/plugin/filter/filter_bpfel_arm64.o
  pkg/plugin/filter/filter_bpfel_x86.o
  pkg/plugin/packetforward/packetforward_bpfel_arm64.o
  pkg/plugin/packetforward/packetforward_bpfel_x86.o
  pkg/plugin/packetparser/packetparser_bpfel_arm64.o
  pkg/plugin/packetparser/packetparser_bpfel_x86.o
Labels: type/fix, priority/0, scope/S

#340 fix: correct selector in PodMonitor
  deploy/manifests/controller/helm/retina/templates/podmonitor.yaml
Labels: type/fix, area/infra, priority/0, scope/S

#343 fix: unconstrain e2e AZ
  .github/workflows/images.yaml
  test/e2e/framework/azure/create-cluster-with-npm.go
  test/e2e/framework/azure/create-cluster.go
  test/e2e/scenarios/retina/retina_scenarios_test.go
Labels: type/fix, area/infra

#342 fix: only invoke Generate once for plugins when reconciling in plugin manager
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/dropreason/dropreason_linux_test.go
  pkg/plugin/packetparser/packetparser_linux.go
  pkg/plugin/packetparser/packetparser_linux_test.go
Labels: type/fix, area/plugins

#341 feat: migrate to Mariner containers
  controller/Dockerfile
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/filter/filter_map_linux.go
  pkg/plugin/packetforward/packetforward_linux.go
  pkg/plugin/packetparser/packetparser_linux.go
  test/image/Dockerfile
Labels: type/enhancement, area/infra, priority/0, scope/M

#358 chore: remove old integration tests
  scripts/create_aks_cluster.sh
  scripts/create_retina_logs.sh
  scripts/install_retina.sh
  scripts/test_retina.sh
  scripts/upgrade_retina.sh
  test/integration/Dockerfile.integration
  test/integration/README.md
  test/integration/annotations/annotation_suite_test.go
  test/integration/annotations/annotations.go
  test/integration/capture/capture_suite_test.go
  test/integration/common/kubemanager.go
  test/integration/common/metrics_model.go
  test/integration/common/model.go
  test/integration/common/types.go
  test/integration/plugins/dns/dns_suite_test.go
  test/integration/plugins/dropreason/dropreason_suite_test.go
  test/integration/plugins/forward/forward_suite_test.go
Labels: area/infra, priority/1, scope/S

#379 fix: pin Windows base images
  controller/Dockerfile
Labels: type/fix, area/infra, priority/0, scope/S

#322 fix: the ebpf program in the tcpretrans plugin failed to load
  pkg/plugin/tcpretrans/tcpretrans_linux.go
Labels: lang/go, type/fix, area/plugins, priority/0, scope/S

#347 chore: move E2E to separate GHA
  .github/workflows/e2e.yaml
  .github/workflows/images.yaml
Labels: type/enhancement, area/infra, priority/1, scope/S

#412 fix: add --name for capture create command examples
  docs/captures/cli.md
  docs/captures/readme.md
Labels: area/documentation

#411 fix: trim blob SAS URL read from mounted secret file
  docs/captures/readme.md
  pkg/capture/outputlocation/blob.go
  pkg/capture/outputlocation/blob_test.go
Labels: type/fix, area/captures, priority/0, scope/S

#381 refactor: pin and alias base images in the Dockerfile
  controller/Dockerfile
Labels: type/enhancement, area/infra, priority/1, scope/S

#308 chore: bump various k8s.io components' version
  controller/main.go
  deploy/manifests/controller/helm/retina/crds/retina.sh_captures.yaml
  deploy/manifests/controller/helm/retina/crds/retina.sh_tracesconfigurations.yaml
  go.mod
  go.sum
  operator/main.go
  pkg/controllers/daemon/retinaendpoint/suite_test.go
  pkg/controllers/operator/retinaendpoint/retinaendpoint_controller.go
  pkg/controllers/operator/retinaendpoint/retinaendpoint_controller_test.go
  test/image/Dockerfile
Labels: area/dependencies, scope/M

#414 test(e2e): add e2e test for latency metrics in advanced scenario
  test/e2e/jobs/jobs.go
  test/e2e/scenarios/dns/scenarios.go
  test/e2e/scenarios/dns/validate-advanced-dns-metric.go
  test/e2e/scenarios/dns/validate-basic-dns-metric.go
  test/e2e/scenarios/latency/scenario.go
  test/e2e/scenarios/latency/validate-latency-metric.go
Labels: area/metrics, area/infra, priority/1, scope/S
