Repository microsoft/retina, pull requests merged in 2024-04, with the labels that each got.

#199 fix(Refactor): Update function comment in Watcher() method
  pkg/watchers/apiserver/apiserver.go
Labels: area/documentation, lang/go, type/fix, priority/2

#211 feat: add trivy
  .github/workflows/trivy.yaml
Labels: type/enhancement, area/infra, priority/1

#129 fix: failed to build binary by make retina-binary
  .gitignore
  Makefile
Labels: type/fix, priority/0

#210 fix: Update CONTRIBUTING
  CONTRIBUTING.md
Labels: area/documentation, type/enhancement, priority/1

#227 docs: clarifications in quick install guide, plus instructions for commit sign-off
  .github/pull_request_template.md
  docs/contributing/readme.md
  docs/installation/setup.md
Labels: area/documentation

#234 fix: metrics module repeats unnecessary reconciliation (#233)
  pkg/controllers/cache/cache.go
Labels: lang/go, type/fix, area/controllers, priority/1

#229 docs: explain how to work with GHCR in forks
  docs/contributing/developing.md
  docs/contributing/readme.md
Labels: area/documentation, type/enhancement, priority/2

#160 feat(cd): sign released container images and Helm chart
  .github/workflows/release-charts.yaml
  .github/workflows/release-images.yaml
  Makefile
  README.md
  docs/installation/verify-signed-images.md
Labels: type/enhancement, area/infra, priority/1

#245 fix: add new site pages to nav
  .gitignore
  site/sidebars.js
Labels: area/documentation, type/fix, lang/javascript, priority/2

#261 feat(helm): Improve resource configuration in chart
  deploy/manifests/controller/helm/retina/templates/daemonset.yaml
  deploy/manifests/controller/helm/retina/templates/operator.yaml
  deploy/manifests/controller/helm/retina/values.yaml
Labels: type/enhancement, area/infra, priority/1

#228 feat(cli): add logs to check portguid
  pkg/plugin/windows/hnsstats/hnsstats_windows.go
Labels: type/enhancement, lang/go, area/plugins, area/windows, priority/1

#268 fix: convert kernel monotonic times to wall time
  internal/ktime/ktime.go
  internal/ktime/ktime_other.go
  internal/ktime/ktime_unix.go
  pkg/plugin/dropreason/_cprog/drop_reason.c
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/packetparser/_cprog/packetparser.c
  pkg/plugin/packetparser/packetparser_linux.go
Labels: type/enhancement, lang/go, type/fix, area/plugins, area/ebpf, priority/0

#275 fix: capture name flag
  cli/cmd/capture/capture.go
  cli/cmd/capture/create.go
  cli/cmd/capture/delete.go
  cli/cmd/capture/download.go
Labels: lang/go, type/fix, area/captures, priority/0

#260 fix: fix cross-platform build image dependency package architecture i…
  controller/Dockerfile.controller
Labels: type/fix, area/infra, priority/1

#276 fix: Don't bypass other tc-bpf programs
  pkg/plugin/packetparser/_cprog/packetparser.c
  pkg/plugin/packetparser/_cprog/packetparser.h
Labels: type/fix, area/ebpf, priority/0

#267 fix: set go version from mod
  .github/workflows/codeql.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/goreleaser.yaml
  .github/workflows/images.yaml
  .github/workflows/release-images.yaml
  .github/workflows/test.yaml
Labels: type/enhancement, area/infra, priority/2

#294 chore: prevent action bash escapes
  .github/workflows/commit-message.yaml
Labels: type/fix, area/infra, priority/1

#272 fix: add secondary IPs for enrichment
  pkg/common/endpoint.go
  pkg/common/ipaddr.go
  pkg/controllers/cache/cache.go
  pkg/controllers/cache/cache_test.go
  pkg/enricher/enricher_test.go
Labels: type/enhancement, area/plugins, priority/1

#301 chore: update to go 1.22
  controller/Dockerfile.controller
  controller/Dockerfile.gogen
  controller/Dockerfile.proto
  controller/Dockerfile.windows-2019
  controller/Dockerfile.windows-2022
  go.mod
  hack/tools/go.mod
  operator/Dockerfile
  operator/Dockerfile.windows-2019
  operator/Dockerfile.windows-2022
  test/image/Dockerfile
  test/integration/Dockerfile.integration
Labels: dependencies

#302 chore: bump github actions version
  .github/workflows/goreleaser.yaml
  .github/workflows/images.yaml
  .github/workflows/release-images.yaml
Labels: dependencies

#264 tool(grafana): test/tooling to ensure dashboards are simplified/importable
  Makefile
  deploy/grafana/dashboards/clusters.json
  deploy/grafana/dashboards/dns.json
  deploy/grafana/dashboards/pod-level.json
  deploy/grafana/dashboards/simplify-grafana-overwrite_test.go
  deploy/grafana/dashboards/simplify-grafana.go
  deploy/grafana/dashboards/simplify-grafana_test.go
Labels: area/infra, area/data-ingestion-and-visualization

#270 fix: reduce number of anypb.New invoke when enriching flows
  pkg/module/metrics/dns.go
  pkg/module/metrics/dns_test.go
  pkg/module/metrics/latency.go
  pkg/module/metrics/latency_test.go
  pkg/plugin/dns/dns_linux.go
  pkg/plugin/dns/dns_linux_test.go
  pkg/plugin/dropreason/dropreason_linux.go
  pkg/plugin/packetparser/packetparser_bpf.o
  pkg/plugin/packetparser/packetparser_linux.go
  pkg/plugin/tcpretrans/tcpretrans_linux.go
  pkg/utils/flow_utils.go
  pkg/utils/utils_linux_test.go
Labels: type/enhancement, area/plugins

#307 fix: rewrite Dockerfile to resolve architecture mismatch issues
  Makefile
  controller/Dockerfile
  controller/Dockerfile.controller
  controller/Dockerfile.windows-2019
  controller/Dockerfile.windows-2022
Labels: type/enhancement, lang/go, area/infra, priority/1, lang/c, scope/L

#269 chore: remove *.o files
  .gitignore
  controller/Dockerfile
  pkg/managers/filtermanager/manager_linux.go
  pkg/managers/filtermanager/manager_linux_test.go
  pkg/managers/filtermanager/manager_windows.go
  pkg/plugin/dropreason/kprobe_bpfel_arm64.o
  pkg/plugin/dropreason/kprobe_bpfel_x86.o
  pkg/plugin/filter/filter_bpfel_arm64.o
  pkg/plugin/filter/filter_bpfel_x86.o
  pkg/plugin/packetforward/packetforward_bpfel_arm64.o
  pkg/plugin/packetforward/packetforward_bpfel_x86.o
  pkg/plugin/packetparser/packetparser_bpfel_arm64.o
  pkg/plugin/packetparser/packetparser_bpfel_x86.o
  test/image/Dockerfile
Labels: type/enhancement, area/ebpf

#323 fix(helm): PodMonitor additional labels YAML
  deploy/manifests/controller/helm/retina/templates/podmonitor.yaml
Labels: type/fix, area/infra, priority/1, scope/S

#320 fix: restructure logger for persistent fields
  controller/main.go
  init/retina/main_linux.go
  pkg/bpf/setup_linux.go
  pkg/log/zap.go
  pkg/log/zap_test.go
Labels: type/enhancement, lang/go, area/infra, priority/2, scope/S
